### ISSUE TITLE
Tester et intégrer angular-touch pour remplacer ngClick (voir description pour lien)

### ISSUE THREAD

**Issue by maallard** [WildCodeSchool/laloupe-0217-Enedis-Mini-Jeux#46]
https://docs.angularjs.org/api/ngTouch

**Comment by Cleclemi28** [comment]
grace au :   <meta name="viewport" content="initial-scale=1, maximum-scale=1"> 
Le click a l'air de beaucoup mieux ce passer ( voir très bien ) a testé pour voir si il faut reellement le modifier
